// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/global/A.vue')['default']
    AboutISaw: typeof import('./src/components/page/blog/AboutISaw.vue')['default']
    ActiveTop: typeof import('./src/components/global/ActiveTop.vue')['default']
    Anno: typeof import('./src/components/page/home/Anno.vue')['default']
    BackTable: typeof import('./src/components/page/back/BackTable.vue')['default']
    BlogHeader: typeof import('./src/components/page/blog/BlogHeader.vue')['default']
    BranchCrumb: typeof import('./src/components/global/BranchCrumb.vue')['default']
    Casual: typeof import('./src/components/global/SideBar/Casual.vue')['default']
    ChangeInfo: typeof import('./src/components/page/user/ChangeInfo.vue')['default']
    Comment: typeof import('./src/components/page/blog/Comment.vue')['default']
    Content: typeof import('./src/components/page/blog/Content.vue')['default']
    Emoji: typeof import('./src/components/global/Emoji/index.vue')['default']
    FlexCol: typeof import('./src/components/global/Layout/FlexCol.vue')['default']
    Footer: typeof import('./src/components/global/Footer.vue')['default']
    Header: typeof import('./src/components/global/Header/index.vue')['default']
    HeaderLogoChange: typeof import('./src/components/page/user/HeaderLogoChange.vue')['default']
    HeadLogo: typeof import('./src/components/global/SideBar/HeadLogo.vue')['default']
    HotList: typeof import('./src/components/page/home/HotList.vue')['default']
    HotSee: typeof import('./src/components/global/SideBar/HotSee.vue')['default']
    Lately: typeof import('./src/components/global/SideBar/Lately/index.vue')['default']
    LatelyData: typeof import('./src/components/page/charts/latelyData.vue')['default']
    List: typeof import('./src/components/page/home/ModuleTo/List.vue')['default']
    LoginRegist: typeof import('./src/components/global/Header/LoginRegist.vue')['default']
    Message: typeof import('./src/components/global/SideBar/TimeLine/Message.vue')['default']
    Module: typeof import('./src/components/global/Module.vue')['default']
    ModuleShow: typeof import('./src/components/page/home/ModuleShow.vue')['default']
    ModuleTo: typeof import('./src/components/page/home/ModuleTo/index.vue')['default']
    Moment: typeof import('./src/components/global/Moment.vue')['default']
    NavHeader: typeof import('./src/components/page/back/NavHeader/index.vue')['default']
    Navigation: typeof import('./src/components/global/Navigation/index.vue')['default']
    NavMenu: typeof import('./src/components/page/back/NavMenu/index.vue')['default']
    Overlay: typeof import('./src/components/global/Overlay.vue')['default']
    Overview: typeof import('./src/components/page/back/overview/overview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/global/Header/Search.vue')['default']
    SelectedGuide: typeof import('./src/components/page/home/SelectedGuide.vue')['default']
    SideBar: typeof import('./src/components/global/SideBar/index.vue')['default']
    SubjectItem: typeof import('./src/components/page/subject/SubjectList/SubjectItem.vue')['default']
    SubjectList: typeof import('./src/components/page/subject/SubjectList/index.vue')['default']
    SwiperBar: typeof import('./src/components/page/home/SwiperBar.vue')['default']
    TagList: typeof import('./src/components/page/createBlog/TagList.vue')['default']
    TalkList: typeof import('./src/components/page/talk/TalkList.vue')['default']
    TimeLine: typeof import('./src/components/global/SideBar/TimeLine/index.vue')['default']
    UserForm: typeof import('./src/components/global/UserForm/index.vue')['default']
    UserHeader: typeof import('./src/components/page/back/NavHeader/UserHeader.vue')['default']
    UserInfo: typeof import('./src/components/page/user/UserInfo.vue')['default']
    WelcomeBar: typeof import('./src/components/page/home/WelcomeBar.vue')['default']
  }
}

export {}
